defilytica/balancer-ops-frontend

- app/payload-builder/add-reward-to-gauge/page.tsx
- app/payload-builder/ccip-bridge/page.tsx
- app/payload-builder/enable-gauge/page.tsx
- app/payload-builder/kill-gauge/page.tsx
- lib/modules/payloadBuilders/CreatePayment.tsx
- lib/modules/web3/contracts/abis/IGnosisSafe.json
- lib/shared/components/btns/SimulateTransactionButton.tsx
- package.json
- pages/api/tenderly/simulate-transactions.ts
- yarn.lock
- Setup of custom API as tenderly uses a secret for its API endpoint
- Can handle most Batch / Safe transactions and simulates them correctly
- Display of status in toast as well as small module
- Failed / successful simulations show public Tenderly link to check
> Tenderly Simulation Integration

- app/api/injector/route.ts
- components/RewardsInjector.tsx
- components/tables/RewardsInjectorTable.tsx
- constants/constants.ts
- types/types.ts
- add hyperlinks for injector and gauges
- add check if distributor is correctly set for the currently active reward token
- add warning if reward token is not configured or if reward distributor is not set correctly for a given gauge
- remove date label for gauges that don't have a "last injection" date yet (1.1.1970)
> Injector viewer improvements

- app/rewards-injector/[...address]/page.tsx
- app/rewards-injector/page.tsx
- components/RewardsInjector.tsx
- components/RewardsInjectorContainer.tsx
- types/interfaces.ts
- allow for direct link views and loading such as /rewards-injector/0xAddress
- state management upgrade to load from container so injector data is only fetched once on state change
> Injector viewer: deep links

- app/api/injector/route.ts
- components/RewardsInjectorContainer.tsx
- make additional rpc call
- pass owner of injector as createdFromSafeAddress target
> Fix: Assign Owner as createdFromSafeAddress in Payload

- app/payload-builder/add-reward-to-gauge/page.tsx
- app/payload-builder/cctp-bridge/page.tsx
- app/payload-builder/enable-gauge/page.tsx
- app/payload-builder/kill-gauge/page.tsx
- components/ChangeSwapFeeModule.tsx
- components/CreatePayment.tsx
- components/RewardsInjectorConfigurator.tsx
- components/btns/SimulateTransactionButton.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- lib/utils/getChainId.ts
- properly parse arrays and simple contract inputs
- handle json parsing and mapping
- tested on all payload types successfully
> Fix Tenderly simulations

- components/RewardsInjector.tsx
- components/RewardsInjectorConfigurator.tsx
- components/tables/RewardsInjectorTable.tsx
- constants/constants.ts
- lib/data/injector/helpers.ts
- add more clear metrics to helpers
- modify maxi safe for payloads
- fix bug with missing injector owner for v1 configurator
> feat: improve v1 infra

- app/api/injector/v1/all/route.ts
- app/api/injector/v1/single/route.ts
- app/api/injector/v2/all/route.ts
- app/api/injector/v2/single/route.ts
- app/rewards-injector/status/page.tsx
- components/RewardsInjector.tsx
- components/RewardsInjectorCard.tsx
- components/RewardsInjectorConfigurator.tsx
- components/RewardsInjectorConfiguratorV2.tsx
- components/RewardsInjectorContainer.tsx
- components/tables/RewardsInjectorTable.tsx
- lib/data/injector/helpers.ts
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- prisma/schema.prisma
- Injector v2 viewer: properly pass gauge pool name
- fix token decimal fetching and value transformations
- properly handle state
- add chain for v2 injectors hyperlink as IDs are non-unique (same ID order per factory)
- Injector v1: fix PR generator folder fix
- Injector v2: fix PR generator folder
> Fix: Clean-up injector v2 issues

- app/payload-builder/payloadHelperFunctions.ts
- components/RewardsInjectorContainer.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- Fix add recipient and type
- fix loading of v2 injector state (incl. token types)
> fix: injector v2 configurator

- app/payload-builder/set-reward-distributor-to-gauge/page.tsx
- components/modal/PRModal.tsx
- constants/constants.ts
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- fix keyword for set reward distributor
- clean-up week number (remove trailing zero)
> Hotfix: pr creation modal fix

- .eslintignore
- .prettierignore
- .prettierrc
- package.json
- yarn.lock
Note: re-run prettier on entire project after other PRs are merged
> feat: add prettier config

- app/page.tsx
- app/payload-builder/page.tsx
- components/navigation/NavItem.tsx
- components/navigation/SidebarContent.tsx
> new welcome page

- abi/ChildChainGaugeInjectorV2Factory.js
- app/api/injector/v2/network/route.ts
- app/injector-creator-v2/page.tsx
- components/AdressInput.tsx
- components/InjectorCreatorModule.tsx
- components/navigation/SidebarContent.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- Main UI for core parameters
- Cross-check for inject token, both on UI and injector level
> Create injector from factory

- app/api/injector/v1/all/route.ts
- components/RewardsInjectorContainer.tsx
> Hotfix: handle deprecated injectors

- components/ChangeSwapFeeV3Module.tsx
- same logic as stablesurge hook
> hotfix: v3 fee manager

- abi/VaultExplorer.js
- app/api/liquidity-buffer/balance/route.ts
- app/api/liquidity-buffer/shares/owner/route.ts
- app/api/liquidity-buffer/shares/total/route.ts
- change VaultExplorer address and ABI to v2
> fix: change VaultExplorer to v2

- components/RewardsInjectorConfigurationViewerV2.tsx
- components/RewardsInjectorContainer.tsx
- components/tables/RewardsInjectorTable.tsx
- Improve table density
- Add timestamp information
- Better mobile viewer, fixed issue with token amounts in mobile
- Configurator: add timestamp for last injection info
> Injector Viewer and Configurator: Better UX

- components/ChangeSwapFeeModule.tsx
- components/ChangeSwapFeeV3Module.tsx
- components/MevCaptureHookConfigurationModule.tsx
- components/RewardsInjectorConfiguratorV2.tsx
- components/StableSurgeHookConfigurationModule.tsx
- constants/constants.ts
- lib/modules/web3/WagmiConfig.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- package.json
- handle state change better
- fix hooks PR creation flow
- remove wagmi config that causes init issues
- replace fallback with public dRPC endpoints for walletconnect
> PR Creation Flow: Bugfixes

- README.md
By adding the badge the wiki will be auto-updated on repo changes
> Feat: Add DeepWiki docs badge

- app/api/amp-factor/route.ts
- app/hooks/amp-factor/useAmpFactor.ts
- app/payload-builder/amp-factor-update-v2/page.tsx
- app/payload-builder/amp-factor-update-v3/page.tsx
- app/payload-builder/page.tsx
- app/payload-builder/payloadHelperFunctions.ts
- components/ChangeAmpFactorModule.tsx
- components/ChangeAmpFactorModuleV2.tsx
- constants/constants.ts
- lib/hooks/validation/useValidateAmpFactor.ts
- lib/hooks/validation/useValidateEndTime.ts
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- provides Amp factor update payload builders for Balancer v2 and v3
- Uses one component for both as they have identical call patterns and only minor safe permissions differences
> Feature: Amp factor payload builder

- components/PermissionsPayloadBuilder.tsx
- fix stringified parsing which breaks pull request data
> Hotfix: Permissions Payload Builder json parsing

- app/payload-builder/composer/ComposerPayloadViewer.tsx
- constants/constants.ts
Added PR constants for Payload Composer.
> fix: fixes PR dialog in composer

- components/tables/HookParametersTable.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- lib/utils/calculateStableSurgeBalanceMetrics.ts
- As per zekraken request, add info on token imbalance for better monitoring
- Based on https://surge-balances.web.app/ 
- Code: https://github.com/zekraken-bot/pool-balance-app/blob/master/src/App.js
> Token Imbalance Calculations

- components/InitializeBufferModule.tsx
- lib/modules/web3/WagmiConfig.tsx
- package.json
- yarn.lock
> buffer init fixes

- app/api/auth/[...nextauth]/route.ts
- auth.ts
- components/modal/PRModal.tsx
- add refresh button (couldn't fully test as my fork is up-to-date
- communicated new secrets for localhost login flow. upadted oauth app on org level for that
> feat: gh refresh and localhost fixes

- package.json
- yarn.lock
- Fixes all moderate dependabot alerts
> feat: security upgrades

- app/api/tenderly/simulate-eoa/route.ts
- app/payload-builder/simulationHelperFunctions.ts
- components/navigation/MobileNav.tsx
- package.json
- yarn.lock
- resolve all high, medium and low severity dependabot alerts
- project linting
> Security Upgrades and Linting: September patch

- app/api/reward-tokens/route.ts
- app/reward-tokens/page.tsx
- components/NetworkSelector.tsx
- components/RewardTokensOverview.tsx
- components/modal/AddRewardsModal.tsx
- components/tables/RewardTokensTable.tsx
- lib/services/apollo/generated/graphql.ts
- lib/services/apollo/generated/schema.graphql
- types/rewardTokenTypes.ts
- add token images for easier reference
- add query params to load "add rewards" modal directly (request from beets)
- fix network modal bug / z-index issue
closes #178
> Improve Reward Token Management

- app/api/address-check/route.ts
- components/MevCaptureHookConfigurationModule.tsx
- components/ReClammModule.tsx
- components/StableSurgeHookConfigurationModule.tsx
- types/interfaces.ts
Checks if owner is `SafeProxy` in StableSurge and MevCapture config modules.
> Check if owner is SafeProxy 

- components/RewardTokensOverview.tsx
- components/modal/AddRewardsModal.tsx
Fixes transaction flow implementation that was badly designed. Now follows nice patter established in buffer init module
Wallet to test approval flow with cancel action:
- Chain: Sonic
- wallet: 0xb5e6b895734409Df411a052195eb4EE7e40d8696
closes #184
> Bugfix: Add Reward Transaction flow
